### ISSUE TITLE
Middleware Integration

### ISSUE THREAD

**Issue by JohnGreenan** [AlignmentSystems/PyEngine#2]
Need effective middleware integration - FIX engine<>middleware<>Core C++ engine proxy

**Comment by da4089** [comment]
There's a few choices here.

AMQP as one of ActiveMQ, Apollo/Artemis, or RabbitMQ is probably easiest.

Tibco EMS, Tibco RV, WebSphere, Solace, etc, etc, might be of interest, depending on the client's system.  Hopefully not though :-)

A direct TCP socket connection would also work ...
