### ISSUE TITLE
DevOps "view" pattern

### ISSUE THREAD

**Issue by JohnGreenan** [AlignmentSystems/PyEngine#3]
Need to have some ability to:
Check on sequence numbers on both sides of a FIX session
Check on session status (session up/down, heartbeating ok, heartbeat 'missed', etc.)

**Comment by da4089** [comment]
See comments on #4 re: REST API and dashboard, plus telnet.

In addition, operational log messages should report all events like unexpected session up/down, missed heartbeats, etc.
