### ISSUE TITLE
DevOps "controller" pattern

### ISSUE THREAD

**Issue by JohnGreenan** [AlignmentSystems/PyEngine#4]
Need to be able to reset sequence numbers
Need to be able to set sequence numbers to a specific number

**Comment by da4089** [comment]
In past lives I've used an internal "tree" model of the controllable parameters, an exposed that tree via both REST and Telnet.

The REST API was then fronted with a dashboard page which had these as menu options on the session.   The telnet interface had a standard sort of command line option to set or reset the sequences for a session.
