### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by JohnGreenan** [AlignmentSystems/PyEngine#5]
Need to be able to implement a logging model that works simply - inbound/outbound - think of log4j, slf4j and the like

Want to be able to pick up specific tag=value pairs for logging - use this as a basis for a grep based DevOps model (spot any messages that are unexpected such as resend requests and the like)

**Comment by da4089** [comment]
I generally like to separate the message logging and everything else.

The built-in Python logging has some limitations (latency, for one).  But it's got some of the capabilities of slf/l4j.

Using syslog as a base model means you can integrate with everything, but doesn't preserve any "semantics" that a more structured format does.  There are structured options, but none of them is as universal as syslog.

For the message logging, I tend towards using a database (Mongo, Postgres, MySQL) and then a simple tool to emit a plain-text format (eg. QuickFIX-style) with filtering.  So, pick CompIDs, time range, tags-required, etc, and it will spit out a text stream that you can dump to file, grep, etc.
