### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by JohnGreenan** [AlignmentSystems/PyEngine#7]
To be determined - will ask prospect on preferences

**Comment by da4089** [comment]
I use generally use PyInstaller for delivery, which means that the interpreter and all modules are packaged into a single executable for the target platform (Linux, Windows, etc).  This can include shared libraries for C/C++ code as well.

This means that installing it has no impact on any other Python in use on the target system, and in fact, that the installed system (or client) doesn't even "know" it's Python.

All that said, I'd strongly recommend Python 3.6 or later, so we can take advantage of the async support, which makes the networking and database access simpler.
