### ISSUE TITLE
SNMP integration

### ISSUE THREAD

**Issue by JohnGreenan** [AlignmentSystems/PyEngine#8]
If note SNMP - what?

**Comment by da4089** [comment]
Adding SNMP is possible.  It's not a great technology in 2019, but it's widely supported for monitoring.

In past lives, I've used a REST API for configuration and SNMP-like reporting.  A dashboard web page can periodically poll the REST API for eg. per-connection statistics, up/down status, etc, etc.

Alternatively, I've also used WebSockets to deliver real-time streaming monitoring to a dashboard page.  That clearly has lower overhead than mindless polling, but it's less simple to integrate than HTTP-fetching-JSON, which works with everything from `curl` upwards ...
