### ISSUE TITLE
Uptime

### ISSUE THREAD

**Issue by JohnGreenan** [AlignmentSystems/PyEngine#9]
Mean-time-between-failure?
Mean-time-to-resolution?
Uptime?
Failover?
High-availability?

**Comment by da4089** [comment]
Expected uptime is at minimum 24 x 5.5, but target is to require an engine restart only for code updates.

Failover / HA is dictated by choice of session logging and configuration mechanisms.  In previous lives, I've used MongoDB or PostgreSQL for these, and that enabled pretty seamless failover between HA engines on different server machines using DNS or a load-balancer.
